import { createContext, useContext, useState } from 'react'

const translations = {
  fr: {
    nav: { services:'Services', about:'À Propos', whyUs:'Pourquoi Nous', contact:'Contact', clientLogin:'Staff Portal', broker:'Courtier en Assurances' },
    hero: {
      eyebrow:'Courtier Agréé — Chanas Assurances S.A.',
      h1_1:'Votre', h1_em:'protection,', h1_2:"notre engagement.",
      desc:"Diko's Assurances SARL vous accompagne dans le choix des meilleures couvertures — auto, habitation, santé et vie — avec un service personnalisé et de proximité.",
      cta:'Obtenir un Devis', services:'Nos Services',
      stats:['Clients Protégés','Types de Couverture','Satisfaction Client'], badge:"Ans d'Expérience",
    },
    services: {
      eyebrow:"Ce que nous offrons", title:"Nos Produits\nd'Assurance",
      subtitle:"Des solutions adaptées à chaque besoin, par des experts à votre écoute.",
      items:[
        { name:'Assurance Auto',      icon:'🚗', desc:"Protection complète pour vos véhicules — responsabilité civile, tous risques, vol et dommages." },
        { name:'Assurance Habitation',icon:'🏠', desc:"Couvrez votre logement contre les sinistres, incendies, inondations et cambriolages." },
        { name:'Assurance Santé',     icon:'🏥', desc:"Remboursements médicaux, hospitalisations, consultations. Une santé bien assurée." },
        { name:'Assurance Vie',       icon:'🛡️', desc:"Protégez l'avenir de vos proches avec des contrats vie sur mesure." },
      ],
    },
    about: {
      eyebrow:'Notre Histoire', title:"Un courtier de\nconfiance, à votre côté",
      body:"Diko's Assurances SARL est un courtier indépendant agréé, partenaire officiel de Chanas Assurances S.A. — l'une des compagnies d'assurance les plus reconnues du Cameroun, certifiée ISO 9001.",
      points:['Conseil indépendant et objectif','Gestion simplifiée de vos contrats','Accompagnement en cas de sinistre','Quatre types de couverture','Service transparent, sans frais cachés'],
      partnerLabel:'Sous la bannière de', visitBtn:'Visiter →',
      chanasSub:"Fondée 1999 · ISO 9001 · 6 milliards FCFA · MINEFI · « Le risque maîtrisé, l'avenir assuré »",
      learnMore:'En savoir plus', partner:'Partenaire Officiel',
    },
    why: {
      eyebrow:'Notre Valeur Ajoutée', title:"Pourquoi Choisir\nDiko's Assurances ?",
      subtitle:"Nous ne vendons pas juste une police — nous construisons une relation de confiance durable.",
      items:[
        { icon:'💬', title:'Conseils Personnalisés', desc:'Chaque client est unique. Nous analysons votre profil pour recommander la couverture la plus adaptée.' },
        { icon:'⚡', title:'Réactivité',             desc:'Devis rapides, traitement efficace des dossiers et suivi constant de vos contrats.' },
        { icon:'🔔', title:'Rappels Automatiques',   desc:'Ne manquez jamais une échéance. Nous vous alertons avant expiration de vos contrats.' },
        { icon:'🤝', title:'Relation de Proximité',  desc:'Un interlocuteur dédié, disponible pour répondre à vos questions en toute transparence.' },
      ],
    },
    contact: {
      eyebrow:'Nous Trouver', title:"Parlons de\nvotre projet",
      subtitle:"Contactez-nous pour un devis gratuit ou toute question relative à vos assurances.",
      address:'Avenue Principale, Douala, Cameroun', phone:'+44 7789806378',
      email:'ewiabeng@yahoo.com', hours:'Lun – Ven : 9h00 – 18h00',
      labels:{ address:'Adresse', phone:'Téléphone', email:'Email', hours:'Horaires' },
      whatsapp:'Écrire sur WhatsApp',
      formTitle:'Demande de Devis Gratuit',
      fields:{ firstName:'Prénom', lastName:'Nom', phone:'Téléphone / WhatsApp', type:"Type d'assurance", message:'Message (optionnel)' },
      placeholders:{ firstName:'Jean', lastName:'Dupont', phone:'+237 600 000 000', message:'Décrivez brièvement vos besoins...' },
      options:['Assurance Auto','Assurance Habitation','Assurance Santé','Assurance Vie'],
      selectDefault:'Sélectionnez...', submit:'Envoyer la Demande →',
      successMsg:'Merci ! Nous vous contacterons très bientôt.',
    },
    footer: { rights:'Tous droits réservés.', partner:'Partenaire Officiel — Chanas Assurances S.A.' },
    login: {
      eyebrow:'Accès Sécurisé', title:"Connexion au\ntableau de bord",
      sub:"Réservé à l'administrateur de Diko's Assurances SARL",
      username:'Identifiant', password:'Mot de Passe', userPlaceholder:'Votre identifiant',
      remember:'Se souvenir de moi', forgot:'Mot de passe oublié ?',
      submit:'Se Connecter →', back:'← Retour au site public',
      security:'🔐 Connexion chiffrée · Accès privé',
      errFields:'⚠️ Veuillez remplir tous les champs.',
      errCreds:'✗ Identifiant ou mot de passe incorrect.',
      successMsg:'✓ Connexion réussie. Redirection...',
      leftTagline:'Gérez vos clients et polices en toute', leftEm:'sérénité.',
      leftDesc:"Tableau de bord privé — suivi des contrats, gestion des clients et rappels d'échéances automatisés.",
      statLabels:['Clients actifs','Types de police','Rappel avant expiration','Données sécurisées'],
      portalLabel:'Espace de Gestion',
    },
    dash: {
      newClient:'+ Nouveau Client', search:'Rechercher un client...',
      nav:{ dashboard:'Tableau de Bord', clients:'Clients', policies:'Polices', expiring:'Échéances', reminders:'Rappels', quotes:'Devis', settings:'Paramètres', publicSite:'Site Public' },
      sections:{ main:'Principal', management:'Gestion', system:'Système' },
      viewTitles:{
        dashboard:['Tableau de Bord',"Vue d'ensemble"],
        clients:['Clients','Gestion des clients'],
        policies:['Polices','Tous les contrats'],
        expiring:['Échéances','Polices expirant bientôt'],
        reminders:['Rappels','Notifications automatiques'],
        quotes:['Devis','Gestion des devis'],
        settings:['Paramètres','Configuration du système'],
      },
      cards:['Clients Total','Polices Actives','Expirent Bientôt','Polices Expirées'],
      cardSubs:['Tous types confondus','Sur 48 contrats','Dans les 30 prochains jours','Non renouvelées'],
      cardTrends:['↑ +3 ce mois','85% actif','Action requise','À relancer'],
      status:{ active:'Actif', expiring:'Expire Bientôt', expired:'Expiré', pending:'En attente' },
      quickLabels:['Nouveau Client','Nouvelle Police','Envoyer Rappel','Générer Devis'],
      quickSubs:['Enregistrer un client','Créer un contrat','Email + WhatsApp','PDF exportable'],
      quickIcons:['👤','📋','🔔','💼'],
      expiringTitle:'⏰ Polices Expirant Bientôt', clientsTitle:'👥 Derniers Clients',
      seeAll:'Voir tout →', seeAllClients:'Voir tous →',
      recentActivity:'Activité Récente', quickActions:'Actions Rapides',
      logout:'Déconnexion',
      modal:{ addClient:'Nouveau Client', addPolicy:'Nouvelle Police', cancel:'Annuler', saveClient:'Enregistrer', savePolicy:'Créer la Police', selectClient:'Sélectionnez un client...' },
      savedClient:'Client enregistré avec succès !', savedPolicy:'Police créée avec succès !',
      th:{ client:'Client', type:'Type', expiry:'Expiration', days:'Jours', status:'Statut', num:'#', name:'Nom Complet', phone:'Téléphone', email:'Email', premium:'Prime (XAF)', policy:'N° Police', start:'Début' },
      activity:[
        { text:'<b>Nouvelle police</b> créée pour Martin Essomba', time:"Aujourd'hui, 09:14", dot:'#2ecc71' },
        { text:'<b>Rappel envoyé</b> à Carine Mballa (expiration dans 8 jours)', time:"Aujourd'hui, 08:30", dot:'#f39c12' },
        { text:'<b>Nouveau client</b> enregistré : Alice Tagne', time:'Hier, 16:45', dot:'#C9A84C' },
        { text:'<b>Police expirée</b> : Samuel Fouda — à relancer', time:'Hier, 09:00', dot:'#e74c3c' },
        { text:'<b>Devis envoyé</b> à Jean-Pierre Nkodo', time:'28 fév, 14:22', dot:'#3498db' },
      ],
      reminderMsg:"Les rappels automatiques (30j, 14j, 7j) seront configurés lors du déploiement.",
      quotesMsg:"Module de génération de devis PDF — Phase 2.",
      settingsMsg:"Configuration email, WhatsApp et préférences de rappel.",
      formLabels:{
        firstName:'Prénom', lastName:'Nom', phone:'Téléphone', email:'Email',
        cni:'N° CNI', address:'Adresse', insuranceType:"Type d'Assurance",
        policyNo:'N° de Police', type:'Type', startDate:'Date de Début',
        expiryDate:"Date d'Expiration", premium:'Prime Annuelle (XAF)', notes:'Notes',
      },
    },
  },
  en: {
    nav: { services:'Services', about:'About', whyUs:'Why Us', contact:'Contact', clientLogin:'Staff Portal', broker:'Insurance Broker' },
    hero: {
      eyebrow:'Accredited Broker — Chanas Assurances S.A.',
      h1_1:'Your', h1_em:'protection,', h1_2:'our commitment.',
      desc:"Diko's Assurances SARL guides you to the best insurance coverage — auto, home, health and life — with a personalised, local service tailored to your needs.",
      cta:'Get a Quote', services:'Our Services',
      stats:['Clients Protected','Coverage Types','Client Satisfaction'], badge:'Years Experience',
    },
    services: {
      eyebrow:'What We Offer', title:'Our Insurance\nProducts',
      subtitle:'Tailored solutions for every need, from experts who listen.',
      items:[
        { name:'Auto Insurance',   icon:'🚗', desc:'Full protection for your vehicles — civil liability, comprehensive cover, theft and damage.' },
        { name:'Home Insurance',   icon:'🏠', desc:'Cover your home against fire, flooding and burglary. Your home deserves the best protection.' },
        { name:'Health Insurance', icon:'🏥', desc:'Medical reimbursements, hospitalisations, consultations. Quality health cover for your family.' },
        { name:'Life Insurance',   icon:'🛡️', desc:"Protect your loved ones' future with tailor-made life policies. Savings and estate planning." },
      ],
    },
    about: {
      eyebrow:'Our Story', title:'A trusted broker,\nby your side',
      body:"Diko's Assurances SARL is a licensed independent broker and official partner of Chanas Assurances S.A. — one of Cameroon's most respected ISO 9001-certified insurers.",
      points:['Independent, objective advice','Simplified contract management','Support in the event of a claim','Four major insurance types','Fast, transparent service, no hidden fees'],
      partnerLabel:'Under the banner of', visitBtn:'Visit →',
      chanasSub:"Founded 1999 · ISO 9001 · 6 billion CFA Francs · MINEFI · 'Risk under control, future assured'",
      learnMore:'Learn more', partner:'Official Partner',
    },
    why: {
      eyebrow:'Our Added Value', title:"Why Choose\nDiko's Assurances?",
      subtitle:"We don't just sell a policy — we build a lasting relationship of trust.",
      items:[
        { icon:'💬', title:'Personalised Advice', desc:'Every client is unique. We analyse your profile to recommend the most suitable coverage.' },
        { icon:'⚡', title:'Speed & Efficiency',  desc:'Fast quotes, efficient processing, and constant monitoring of your contracts and renewals.' },
        { icon:'🔔', title:'Automatic Reminders', desc:'Never miss a renewal. We alert you before your contracts expire to ensure continuous protection.' },
        { icon:'🤝', title:'Local Relationship',  desc:'A dedicated contact, always available to answer your questions with complete transparency.' },
      ],
    },
    contact: {
      eyebrow:'Find Us', title:"Let's talk about\nyour needs",
      subtitle:'Contact us for a free quote or any insurance-related question.',
      address:'Main Avenue, Douala, Cameroon', phone:'+237 600 000 000',
      email:'contact@dikosassurances.com', hours:'Mon – Fri: 8:00am – 6:00pm',
      labels:{ address:'Address', phone:'Phone', email:'Email', hours:'Opening Hours' },
      whatsapp:'Chat on WhatsApp',
      formTitle:'Free Quote Request',
      fields:{ firstName:'First Name', lastName:'Last Name', phone:'Phone / WhatsApp', type:'Insurance type', message:'Message (optional)' },
      placeholders:{ firstName:'John', lastName:'Smith', phone:'+237 600 000 000', message:'Briefly describe your needs...' },
      options:['Auto Insurance','Home Insurance','Health Insurance','Life Insurance'],
      selectDefault:'Select...', submit:'Send Request →',
      successMsg:'Thank you! We will get back to you very soon.',
    },
    footer: { rights:'All rights reserved.', partner:'Official Partner — Chanas Assurances S.A.' },
    login: {
      eyebrow:'Secure Access', title:'Sign in to your\ndashboard',
      sub:"Restricted to the administrator of Diko's Assurances SARL",
      username:'Username', password:'Password', userPlaceholder:'Your username',
      remember:'Remember me', forgot:'Forgot password?',
      submit:'Sign In →', back:'← Back to public site',
      security:'🔐 Encrypted connection · Private access',
      errFields:'⚠️ Please fill in all fields.',
      errCreds:'✗ Incorrect username or password.',
      successMsg:'✓ Login successful. Redirecting...',
      leftTagline:'Manage your clients and policies with', leftEm:'confidence.',
      leftDesc:'Private management portal — contract tracking, client management and automated renewal reminders.',
      statLabels:['Active clients','Policy types','Reminder before expiry','Secured data'],
      portalLabel:'Management Portal',
    },
    dash: {
      newClient:'+ New Client', search:'Search a client...',
      nav:{ dashboard:'Dashboard', clients:'Clients', policies:'Policies', expiring:'Renewals', reminders:'Reminders', quotes:'Quotes', settings:'Settings', publicSite:'Public Site' },
      sections:{ main:'Main', management:'Management', system:'System' },
      viewTitles:{
        dashboard:['Dashboard','Overview'],
        clients:['Clients','Client management'],
        policies:['Policies','All contracts'],
        expiring:['Renewals','Policies expiring soon'],
        reminders:['Reminders','Automatic notifications'],
        quotes:['Quotes','Quote management'],
        settings:['Settings','System configuration'],
      },
      cards:['Total Clients','Active Policies','Expiring Soon','Expired Policies'],
      cardSubs:['All types combined','Out of 48 contracts','In the next 30 days','Not renewed'],
      cardTrends:['↑ +3 this month','85% active','Action required','To follow up'],
      status:{ active:'Active', expiring:'Expiring Soon', expired:'Expired', pending:'Pending' },
      quickLabels:['New Client','New Policy','Send Reminder','Generate Quote'],
      quickSubs:['Register a client','Create a contract','Email + WhatsApp','Exportable PDF'],
      quickIcons:['👤','📋','🔔','💼'],
      expiringTitle:'⏰ Policies Expiring Soon', clientsTitle:'👥 Recently Registered Clients',
      seeAll:'See all →', seeAllClients:'See all →',
      recentActivity:'Recent Activity', quickActions:'Quick Actions',
      logout:'Log out',
      modal:{ addClient:'New Client', addPolicy:'New Policy', cancel:'Cancel', saveClient:'Save Client', savePolicy:'Create Policy', selectClient:'Select a client...' },
      savedClient:'Client saved successfully!', savedPolicy:'Policy created successfully!',
      th:{ client:'Client', type:'Type', expiry:'Expiry', days:'Days', status:'Status', num:'#', name:'Full Name', phone:'Phone', email:'Email', premium:'Premium (XAF)', policy:'Policy No.', start:'Start' },
      activity:[
        { text:'<b>New policy</b> created for Martin Essomba', time:'Today, 09:14', dot:'#2ecc71' },
        { text:'<b>Reminder sent</b> to Carine Mballa (expiring in 8 days)', time:'Today, 08:30', dot:'#f39c12' },
        { text:'<b>New client</b> registered: Alice Tagne', time:'Yesterday, 16:45', dot:'#C9A84C' },
        { text:'<b>Policy expired</b>: Samuel Fouda — follow up needed', time:'Yesterday, 09:00', dot:'#e74c3c' },
        { text:'<b>Quote sent</b> to Jean-Pierre Nkodo', time:'28 Feb, 14:22', dot:'#3498db' },
      ],
      reminderMsg:'Automatic reminders (30d, 14d, 7d) will be configured at deployment.',
      quotesMsg:'PDF quote generation module — Phase 2.',
      settingsMsg:'Email, WhatsApp and reminder preference configuration.',
      formLabels:{
        firstName:'First Name', lastName:'Last Name', phone:'Phone', email:'Email',
        cni:'ID Number', address:'Address', insuranceType:'Insurance Type',
        policyNo:'Policy Number', type:'Type', startDate:'Start Date',
        expiryDate:'Expiry Date', premium:'Annual Premium (XAF)', notes:'Notes',
      },
    },
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('fr')
  const t = translations[lang]
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}
